[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x767676"
red = "0xaf5f87"
green = "0x87af87"
yellow = "0xd7af5f"
blue = "0x729fcf"
magenta = "0xaf87d7"
cyan = "0x34e2e2"
white = "0xc6c6c6"

[colors.cursor]
cursor = "0xc6c6c6"
text = "0x262626"

[colors.normal]
black = "0x262626"
red = "0xac2c2c"
green = "0x4e9a06"
yellow = "0xc4a000"
blue = "0x3465a4"
magenta = "0x75507b"
cyan = "0x389aad"
white = "0x626262"

[colors.primary]
background = "0x262626"
foreground = "0xc6c6c6"

[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[font]
size = 13.5

[font.normal]
family = "JetBrains Mono"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 100000

[window]
dynamic_title = true
title = "Terminal"

[general]
live_config_reload = true
